/////////////////////////////////////
// ExportXlsx生成
// http://blog.ihaiu.com/tool-ExportXlsx
/////////////////////////////////////
var configs;
(function (configs) {
    /// 配置读取器列表
    var ConfigManagerList = /** @class */ (function () {
        function ConfigManagerList() {
            // 读取器列表
            this.renders = [];
            this.activities = new configs.ActivitiesConfigReader();
            this.actor = new configs.ActorConfigReader();
            this.actorAssets = new configs.ActorAssetsConfigReader();
            this.actorLevel = new configs.ActorLevelConfigReader();
            this.actorLoyalty = new configs.ActorLoyaltyConfigReader();
            this.actorProficiency = new configs.ActorProficiencyConfigReader();
            this.actorTrain = new configs.ActorTrainConfigReader();
            this.avatar = new configs.AvatarConfigReader();
            this.battleLevel = new configs.BattleLevelConfigReader();
            this.battleShootType = new configs.BattleShootTypeConfigReader();
            this.blockLevel = new configs.BlockLevelConfigReader();
            this.blockRankingList = new configs.BlockRankingListConfigReader();
            this.blockWords = new configs.BlockWordsConfigReader();
            this.buildingEffect = new configs.BuildingEffectConfigReader();
            this.buildingLevel = new configs.BuildingLevelConfigReader();
            this.business = new configs.BusinessConfigReader();
            this.cinema = new configs.CinemaConfigReader();
            this.city = new configs.CityConfigReader();
            this.cityPopularize = new configs.CityPopularizeConfigReader();
            this.compound = new configs.CompoundConfigReader();
            this.cooperateReward = new configs.CooperateRewardConfigReader();
            this.cooperateTask = new configs.CooperateTaskConfigReader();
            this.country = new configs.CountryConfigReader();
            this.dailySign = new configs.DailySignConfigReader();
            this.dialogue = new configs.DialogueConfigReader();
            this.floor = new configs.FloorConfigReader();
            this.gameLevel = new configs.GameLevelConfigReader();
            this.gameRandomName = new configs.GameRandomNameConfigReader();
            this.giftPackage = new configs.GiftPackageConfigReader();
            this.global = new configs.GlobalConfigReader();
            this.guidesystem = new configs.GuidesystemConfigReader();
            this.headPortrait = new configs.HeadPortraitConfigReader();
            this.item = new configs.ItemConfigReader();
            this.loader = new configs.LoaderConfigReader();
            this.loading = new configs.LoadingConfigReader();
            this.mail = new configs.MailConfigReader();
            this.maintask = new configs.MaintaskConfigReader();
            this.meeting = new configs.MeetingConfigReader();
            this.meetingGame = new configs.MeetingGameConfigReader();
            this.meetingRewards = new configs.MeetingRewardsConfigReader();
            this.meetingText = new configs.MeetingTextConfigReader();
            this.menu = new configs.MenuConfigReader();
            this.movieAdaptationMsg = new configs.MovieAdaptationMsgConfigReader();
            this.movieAudienceEvaluation = new configs.MovieAudienceEvaluationConfigReader();
            this.movieDailyReward = new configs.MovieDailyRewardConfigReader();
            this.movieDrop = new configs.MovieDropConfigReader();
            this.movieExpect = new configs.MovieExpectConfigReader();
            this.movieLicence = new configs.MovieLicenceConfigReader();
            this.movieMediaVisit = new configs.MovieMediaVisitConfigReader();
            this.movieMidiaEvaluation = new configs.MovieMidiaEvaluationConfigReader();
            this.movieMidiaEvaluationMsg = new configs.MovieMidiaEvaluationMsgConfigReader();
            this.moviePopularize = new configs.MoviePopularizeConfigReader();
            this.movieShootType = new configs.MovieShootTypeConfigReader();
            this.msg = new configs.MsgConfigReader();
            this.msgProtoError = new configs.MsgProtoErrorConfigReader();
            this.npc = new configs.NpcConfigReader();
            this.order = new configs.OrderConfigReader();
            this.orderComplete = new configs.OrderCompleteConfigReader();
            this.oscar = new configs.OscarConfigReader();
            this.perform = new configs.PerformConfigReader();
            this.playerDefault = new configs.PlayerDefaultConfigReader();
            this.playerLevel = new configs.PlayerLevelConfigReader();
            this.position = new configs.PositionConfigReader();
            this.produce = new configs.ProduceConfigReader();
            this.produceLevel = new configs.ProduceLevelConfigReader();
            this.produceSouvenir = new configs.ProduceSouvenirConfigReader();
            this.property = new configs.PropertyConfigReader();
            this.randomName = new configs.RandomNameConfigReader();
            this.randomSurname = new configs.RandomSurnameConfigReader();
            this.recharge = new configs.RechargeConfigReader();
            this.secretary = new configs.SecretaryConfigReader();
            this.secretaryGift = new configs.SecretaryGiftConfigReader();
            this.secretaryText = new configs.SecretaryTextConfigReader();
            this.secretaryType = new configs.SecretaryTypeConfigReader();
            this.serverRankingList = new configs.ServerRankingListConfigReader();
            this.settingDefault = new configs.SettingDefaultConfigReader();
            this.settingText = new configs.SettingTextConfigReader();
            this.sevenDays = new configs.SevenDaysConfigReader();
            this.sevenDaysText = new configs.SevenDaysTextConfigReader();
            this.shop = new configs.ShopConfigReader();
            this.skill = new configs.SkillConfigReader();
            this.skillEffect = new configs.SkillEffectConfigReader();
            this.skillTrigger = new configs.SkillTriggerConfigReader();
            this.speak = new configs.SpeakConfigReader();
            this.starCon = new configs.StarConConfigReader();
            this.story = new configs.StoryConfigReader();
            this.storyCharacters = new configs.StoryCharactersConfigReader();
            this.storyGoals = new configs.StoryGoalsConfigReader();
            this.storyline = new configs.StorylineConfigReader();
            this.storyRate = new configs.StoryRateConfigReader();
            this.storyStackItem = new configs.StoryStackItemConfigReader();
            this.storyStackSort = new configs.StoryStackSortConfigReader();
            this.storyTask = new configs.StoryTaskConfigReader();
            this.street = new configs.StreetConfigReader();
            this.task = new configs.TaskConfigReader();
            this.taskComplete = new configs.TaskCompleteConfigReader();
            this.test = new configs.TestConfigReader();
            this.type = new configs.TypeConfigReader();
            this.visit = new configs.VisitConfigReader();
        }
        // 初始化读取器列表
        ConfigManagerList.prototype.initList = function () {
            this.renders.push(this.activities);
            this.renders.push(this.actor);
            this.renders.push(this.actorAssets);
            this.renders.push(this.actorLevel);
            this.renders.push(this.actorLoyalty);
            this.renders.push(this.actorProficiency);
            this.renders.push(this.actorTrain);
            this.renders.push(this.avatar);
            this.renders.push(this.battleLevel);
            this.renders.push(this.battleShootType);
            this.renders.push(this.blockLevel);
            this.renders.push(this.blockRankingList);
            this.renders.push(this.blockWords);
            this.renders.push(this.buildingEffect);
            this.renders.push(this.buildingLevel);
            this.renders.push(this.business);
            this.renders.push(this.cinema);
            this.renders.push(this.city);
            this.renders.push(this.cityPopularize);
            this.renders.push(this.compound);
            this.renders.push(this.cooperateReward);
            this.renders.push(this.cooperateTask);
            this.renders.push(this.country);
            this.renders.push(this.dailySign);
            this.renders.push(this.dialogue);
            this.renders.push(this.floor);
            this.renders.push(this.gameLevel);
            this.renders.push(this.gameRandomName);
            this.renders.push(this.giftPackage);
            this.renders.push(this.global);
            this.renders.push(this.guidesystem);
            this.renders.push(this.headPortrait);
            this.renders.push(this.item);
            this.renders.push(this.loader);
            this.renders.push(this.loading);
            this.renders.push(this.mail);
            this.renders.push(this.maintask);
            this.renders.push(this.meeting);
            this.renders.push(this.meetingGame);
            this.renders.push(this.meetingRewards);
            this.renders.push(this.meetingText);
            this.renders.push(this.menu);
            this.renders.push(this.movieAdaptationMsg);
            this.renders.push(this.movieAudienceEvaluation);
            this.renders.push(this.movieDailyReward);
            this.renders.push(this.movieDrop);
            this.renders.push(this.movieExpect);
            this.renders.push(this.movieLicence);
            this.renders.push(this.movieMediaVisit);
            this.renders.push(this.movieMidiaEvaluation);
            this.renders.push(this.movieMidiaEvaluationMsg);
            this.renders.push(this.moviePopularize);
            this.renders.push(this.movieShootType);
            this.renders.push(this.msg);
            this.renders.push(this.msgProtoError);
            this.renders.push(this.npc);
            this.renders.push(this.order);
            this.renders.push(this.orderComplete);
            this.renders.push(this.oscar);
            this.renders.push(this.perform);
            this.renders.push(this.playerDefault);
            this.renders.push(this.playerLevel);
            this.renders.push(this.position);
            this.renders.push(this.produce);
            this.renders.push(this.produceLevel);
            this.renders.push(this.produceSouvenir);
            this.renders.push(this.property);
            this.renders.push(this.randomName);
            this.renders.push(this.randomSurname);
            this.renders.push(this.recharge);
            this.renders.push(this.secretary);
            this.renders.push(this.secretaryGift);
            this.renders.push(this.secretaryText);
            this.renders.push(this.secretaryType);
            this.renders.push(this.serverRankingList);
            this.renders.push(this.settingDefault);
            this.renders.push(this.settingText);
            this.renders.push(this.sevenDays);
            this.renders.push(this.sevenDaysText);
            this.renders.push(this.shop);
            this.renders.push(this.skill);
            this.renders.push(this.skillEffect);
            this.renders.push(this.skillTrigger);
            this.renders.push(this.speak);
            this.renders.push(this.starCon);
            this.renders.push(this.story);
            this.renders.push(this.storyCharacters);
            this.renders.push(this.storyGoals);
            this.renders.push(this.storyline);
            this.renders.push(this.storyRate);
            this.renders.push(this.storyStackItem);
            this.renders.push(this.storyStackSort);
            this.renders.push(this.storyTask);
            this.renders.push(this.street);
            this.renders.push(this.task);
            this.renders.push(this.taskComplete);
            this.renders.push(this.test);
            this.renders.push(this.type);
            this.renders.push(this.visit);
        };
        return ConfigManagerList;
    }());
    configs.ConfigManagerList = ConfigManagerList;
})(configs || (configs = {}));
//# sourceMappingURL=ConfigManagerList.js.map